version: '3.7'

services:
  mariadb:
    # production
    image: 8ct8pus/mariadb-alpine:1.0.7
    # development image
    #image: mariadb-alpine:dev
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - ROOT_PASSWORD=123
    volumes:
      # expose mariadb config to host
      - ./docker/etc/:/docker/etc/
      # expose mariadb log to host
      - ./docker/log/:/var/log/
      # save mariadb database to named volume
      - database:/var/lib/mysql/
volumes:
  database:
